// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCecrpS20DoxDnibK88AAYq2BjydEk7jdU',
    appId: '1:40698156436:web:aeee0958afcc6be67aab81',
    messagingSenderId: '40698156436',
    projectId: 'ecorecycle-c7092',
    authDomain: 'ecorecycle-c7092.firebaseapp.com',
    storageBucket: 'ecorecycle-c7092.appspot.com',
    measurementId: 'G-1V0F28F7TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaB3BGfyPlxmk4PjNonjkxasUeBNpFi2o',
    appId: '1:40698156436:android:6783b26b2a88c8647aab81',
    messagingSenderId: '40698156436',
    projectId: 'ecorecycle-c7092',
    storageBucket: 'ecorecycle-c7092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHgFVB83H82CcF7MxvSh4uURLoAaw_2jk',
    appId: '1:40698156436:ios:3cb15119d4e68ba57aab81',
    messagingSenderId: '40698156436',
    projectId: 'ecorecycle-c7092',
    storageBucket: 'ecorecycle-c7092.appspot.com',
    iosBundleId: 'com.example.ecorecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHgFVB83H82CcF7MxvSh4uURLoAaw_2jk',
    appId: '1:40698156436:ios:3cb15119d4e68ba57aab81',
    messagingSenderId: '40698156436',
    projectId: 'ecorecycle-c7092',
    storageBucket: 'ecorecycle-c7092.appspot.com',
    iosBundleId: 'com.example.ecorecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCecrpS20DoxDnibK88AAYq2BjydEk7jdU',
    appId: '1:40698156436:web:566b5f00b9b169ff7aab81',
    messagingSenderId: '40698156436',
    projectId: 'ecorecycle-c7092',
    authDomain: 'ecorecycle-c7092.firebaseapp.com',
    storageBucket: 'ecorecycle-c7092.appspot.com',
    measurementId: 'G-48Y77W5BBL',
  );

}